# Generated by Django 3.0.5 on 2022-12-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_pizza_pizza_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='pizza_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
