# Generated by Django 3.0.5 on 2022-12-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_auto_20221210_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='pizza_comment',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
